#!/usr/bin/env python

import socket
import sys, hashlib


s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect(("192.168.6.254", 5038))
s.settimeout(.5)
FILE = s.makefile("rw", 8096)
FILE.write("Action: Login\r\nUsername: test\r\nSecret: test\r\nEvents: On\r\n\r\n")
FILE.flush()
print "Starting to Receive ...\n"
AVDict = {}

while 1:
    try:
        data = FILE.readline()
        results = data.strip().split(": ")

        try:
            AVDict[results[0]].append(results[1])
        except KeyError:
            AVDict[results[0]] = results[1];
        except AttributeError:
            continue
        except:
            print "[1001] ", sys.exc_info()[0]

    except IndexError:
        try:
            print "AVDict is:", AVDict
            if AVDict['ChannelState'] == '4' and AVDict['ChannelStateDesc'] == 'Ring':
                print('Sending Accounting for ANI number %s' % AVDict['CallerIDNum'])

            AVDict.clear()
            continue
        except:
            try:
                del AVDict[:]
            except TypeError:
                continue
            except:
                print "[1003]  ", sys.exc_info()[0]
                continue
    except:
        # print "[1004]  ", sys.exc_info()[0]
        continue;

FILE.close()